/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface EmergencyAlert {
    id: bigint;
    alertType: string;
    authorId?: Principal;
    description: string;
    timestamp: Time;
    location: string;
}
export type Time = bigint;
export interface BloodDonor {
    id: bigint;
    bloodType: string;
    contact: string;
    city: string;
    name: string;
    registeredAt: Time;
}
export interface EmergencyContact {
    id: bigint;
    relationship: string;
    ownerPrincipal: Principal;
    name: string;
    createdAt: bigint;
    phone: string;
}
export interface Hospital {
    id: bigint;
    lat: number;
    lng: number;
    contact: string;
    name: string;
    bedsAvailable: bigint;
    address: string;
}
export interface Volunteer {
    id: bigint;
    city: string;
    name: string;
    isActive: boolean;
    skills: Array<string>;
}
export interface SOSEvent {
    id: bigint;
    lat: number;
    lng: number;
    userId?: Principal;
    timestamp: Time;
}
export interface UserProfile {
    contact: string;
    city: string;
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    /**
     * / Add a new emergency contact for authenticated user. Returns contact ID.
     */
    addEmergencyContact(name: string, phone: string, relationship: string): Promise<bigint>;
    /**
     * / Add a hospital. Admin only.
     */
    addHospital(hospital: Hospital): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Get hospitals sorted by proximity (distance calculation done client-side).
     * / Public read.
     */
    findHospitalsByDistance(lat: number, lng: number): Promise<Array<Hospital>>;
    /**
     * / Get all blood donors. Public read.
     */
    getBloodDonors(): Promise<Array<BloodDonor>>;
    /**
     * / Get the calling user's own profile. Requires authenticated user.
     */
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Get summary statistics for the dashboard. Public read.
     */
    getDashboardStats(): Promise<{
        hospitalCount: bigint;
        volunteerCount: bigint;
        availableBeds: bigint;
        donorCount: bigint;
    }>;
    /**
     * / Get donors filtered by blood type. Public read.
     */
    getDonorsByBloodType(bloodType: string): Promise<Array<BloodDonor>>;
    /**
     * / Get all emergency alerts sorted by most recent first. Public read.
     */
    getEmergencyAlerts(): Promise<Array<EmergencyAlert>>;
    /**
     * / Admin/internal function to get emergency contacts for a specific principal
     */
    getEmergencyContactsByPrincipal(userPrincipal: Principal): Promise<Array<EmergencyContact>>;
    /**
     * / Get all hospitals. Public read.
     */
    getHospitals(): Promise<Array<Hospital>>;
    /**
     * / Get all emergency contacts for the calling user.
     */
    getMyEmergencyContacts(): Promise<Array<EmergencyContact>>;
    /**
     * / Get all SOS events. Admin only (sensitive location data).
     */
    getSOSEvents(): Promise<Array<SOSEvent>>;
    /**
     * / Fetch any user's profile. Users can only view their own; admins can view anyone's.
     */
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    /**
     * / Get all volunteers. Public read.
     */
    getVolunteers(): Promise<Array<Volunteer>>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Post an emergency alert. Requires authenticated user.
     */
    postEmergencyAlert(alert: EmergencyAlert): Promise<bigint>;
    /**
     * / Record an SOS event. Accessible to everyone including unauthenticated
     * / users because SOS must work before login.
     */
    recordSOS(sos: SOSEvent): Promise<bigint>;
    /**
     * / Register as a blood donor. Requires authenticated user.
     */
    registerBloodDonor(donor: BloodDonor): Promise<bigint>;
    /**
     * / Register as a volunteer. Requires authenticated user.
     */
    registerVolunteer(volunteer: Volunteer): Promise<bigint>;
    /**
     * / Remove an emergency contact by its ID for the calling user.
     */
    removeEmergencyContact(contactId: bigint): Promise<void>;
    /**
     * / Save / update the calling user's own profile. Requires authenticated user.
     */
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    /**
     * / Update an existing hospital. Admin only.
     */
    updateHospital(hospital: Hospital): Promise<void>;
}
import type { EmergencyAlert as _EmergencyAlert, SOSEvent as _SOSEvent, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addEmergencyContact(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addEmergencyContact(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEmergencyContact(arg0, arg1, arg2);
            return result;
        }
    }
    async addHospital(arg0: Hospital): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addHospital(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHospital(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async findHospitalsByDistance(arg0: number, arg1: number): Promise<Array<Hospital>> {
        if (this.processError) {
            try {
                const result = await this.actor.findHospitalsByDistance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findHospitalsByDistance(arg0, arg1);
            return result;
        }
    }
    async getBloodDonors(): Promise<Array<BloodDonor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBloodDonors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBloodDonors();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<{
        hospitalCount: bigint;
        volunteerCount: bigint;
        availableBeds: bigint;
        donorCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getDonorsByBloodType(arg0: string): Promise<Array<BloodDonor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonorsByBloodType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonorsByBloodType(arg0);
            return result;
        }
    }
    async getEmergencyAlerts(): Promise<Array<EmergencyAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmergencyAlerts();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmergencyAlerts();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmergencyContactsByPrincipal(arg0: Principal): Promise<Array<EmergencyContact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmergencyContactsByPrincipal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmergencyContactsByPrincipal(arg0);
            return result;
        }
    }
    async getHospitals(): Promise<Array<Hospital>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHospitals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHospitals();
            return result;
        }
    }
    async getMyEmergencyContacts(): Promise<Array<EmergencyContact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyEmergencyContacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyEmergencyContacts();
            return result;
        }
    }
    async getSOSEvents(): Promise<Array<SOSEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSOSEvents();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSOSEvents();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVolunteers(): Promise<Array<Volunteer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVolunteers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVolunteers();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async postEmergencyAlert(arg0: EmergencyAlert): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.postEmergencyAlert(to_candid_EmergencyAlert_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postEmergencyAlert(to_candid_EmergencyAlert_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async recordSOS(arg0: SOSEvent): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSOS(to_candid_SOSEvent_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSOS(to_candid_SOSEvent_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async registerBloodDonor(arg0: BloodDonor): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerBloodDonor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerBloodDonor(arg0);
            return result;
        }
    }
    async registerVolunteer(arg0: Volunteer): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerVolunteer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerVolunteer(arg0);
            return result;
        }
    }
    async removeEmergencyContact(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeEmergencyContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeEmergencyContact(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateHospital(arg0: Hospital): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHospital(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHospital(arg0);
            return result;
        }
    }
}
function from_candid_EmergencyAlert_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmergencyAlert): EmergencyAlert {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_SOSEvent_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SOSEvent): SOSEvent {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    lat: number;
    lng: number;
    userId: [] | [Principal];
    timestamp: _Time;
}): {
    id: bigint;
    lat: number;
    lng: number;
    userId?: Principal;
    timestamp: Time;
} {
    return {
        id: value.id,
        lat: value.lat,
        lng: value.lng,
        userId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.userId)),
        timestamp: value.timestamp
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    alertType: string;
    authorId: [] | [Principal];
    description: string;
    timestamp: _Time;
    location: string;
}): {
    id: bigint;
    alertType: string;
    authorId?: Principal;
    description: string;
    timestamp: Time;
    location: string;
} {
    return {
        id: value.id,
        alertType: value.alertType,
        authorId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.authorId)),
        description: value.description,
        timestamp: value.timestamp,
        location: value.location
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SOSEvent>): Array<SOSEvent> {
    return value.map((x)=>from_candid_SOSEvent_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmergencyAlert>): Array<EmergencyAlert> {
    return value.map((x)=>from_candid_EmergencyAlert_n7(_uploadFile, _downloadFile, x));
}
function to_candid_EmergencyAlert_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmergencyAlert): _EmergencyAlert {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_SOSEvent_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SOSEvent): _SOSEvent {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    alertType: string;
    authorId?: Principal;
    description: string;
    timestamp: Time;
    location: string;
}): {
    id: bigint;
    alertType: string;
    authorId: [] | [Principal];
    description: string;
    timestamp: _Time;
    location: string;
} {
    return {
        id: value.id,
        alertType: value.alertType,
        authorId: value.authorId ? candid_some(value.authorId) : candid_none(),
        description: value.description,
        timestamp: value.timestamp,
        location: value.location
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    lat: number;
    lng: number;
    userId?: Principal;
    timestamp: Time;
}): {
    id: bigint;
    lat: number;
    lng: number;
    userId: [] | [Principal];
    timestamp: _Time;
} {
    return {
        id: value.id,
        lat: value.lat,
        lng: value.lng,
        userId: value.userId ? candid_some(value.userId) : candid_none(),
        timestamp: value.timestamp
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
