/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Hospital = IDL.Record({
  'id' : IDL.Nat,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'bedsAvailable' : IDL.Nat,
  'address' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BloodDonor = IDL.Record({
  'id' : IDL.Nat,
  'bloodType' : IDL.Text,
  'contact' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'registeredAt' : Time,
});
export const UserProfile = IDL.Record({
  'contact' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
});
export const EmergencyAlert = IDL.Record({
  'id' : IDL.Nat,
  'alertType' : IDL.Text,
  'authorId' : IDL.Opt(IDL.Principal),
  'description' : IDL.Text,
  'timestamp' : Time,
  'location' : IDL.Text,
});
export const EmergencyContact = IDL.Record({
  'id' : IDL.Nat,
  'relationship' : IDL.Text,
  'ownerPrincipal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'phone' : IDL.Text,
});
export const SOSEvent = IDL.Record({
  'id' : IDL.Nat,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'userId' : IDL.Opt(IDL.Principal),
  'timestamp' : Time,
});
export const Volunteer = IDL.Record({
  'id' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'skills' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEmergencyContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addHospital' : IDL.Func([Hospital], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'findHospitalsByDistance' : IDL.Func(
      [IDL.Float64, IDL.Float64],
      [IDL.Vec(Hospital)],
      ['query'],
    ),
  'getBloodDonors' : IDL.Func([], [IDL.Vec(BloodDonor)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'hospitalCount' : IDL.Nat,
          'volunteerCount' : IDL.Nat,
          'availableBeds' : IDL.Nat,
          'donorCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getDonorsByBloodType' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BloodDonor)],
      ['query'],
    ),
  'getEmergencyAlerts' : IDL.Func([], [IDL.Vec(EmergencyAlert)], ['query']),
  'getEmergencyContactsByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(EmergencyContact)],
      ['query'],
    ),
  'getHospitals' : IDL.Func([], [IDL.Vec(Hospital)], ['query']),
  'getMyEmergencyContacts' : IDL.Func(
      [],
      [IDL.Vec(EmergencyContact)],
      ['query'],
    ),
  'getSOSEvents' : IDL.Func([], [IDL.Vec(SOSEvent)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVolunteers' : IDL.Func([], [IDL.Vec(Volunteer)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'postEmergencyAlert' : IDL.Func([EmergencyAlert], [IDL.Nat], []),
  'recordSOS' : IDL.Func([SOSEvent], [IDL.Nat], []),
  'registerBloodDonor' : IDL.Func([BloodDonor], [IDL.Nat], []),
  'registerVolunteer' : IDL.Func([Volunteer], [IDL.Nat], []),
  'removeEmergencyContact' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateHospital' : IDL.Func([Hospital], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Hospital = IDL.Record({
    'id' : IDL.Nat,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'bedsAvailable' : IDL.Nat,
    'address' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BloodDonor = IDL.Record({
    'id' : IDL.Nat,
    'bloodType' : IDL.Text,
    'contact' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'registeredAt' : Time,
  });
  const UserProfile = IDL.Record({
    'contact' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
  });
  const EmergencyAlert = IDL.Record({
    'id' : IDL.Nat,
    'alertType' : IDL.Text,
    'authorId' : IDL.Opt(IDL.Principal),
    'description' : IDL.Text,
    'timestamp' : Time,
    'location' : IDL.Text,
  });
  const EmergencyContact = IDL.Record({
    'id' : IDL.Nat,
    'relationship' : IDL.Text,
    'ownerPrincipal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'phone' : IDL.Text,
  });
  const SOSEvent = IDL.Record({
    'id' : IDL.Nat,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'userId' : IDL.Opt(IDL.Principal),
    'timestamp' : Time,
  });
  const Volunteer = IDL.Record({
    'id' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'skills' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEmergencyContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addHospital' : IDL.Func([Hospital], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'findHospitalsByDistance' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [IDL.Vec(Hospital)],
        ['query'],
      ),
    'getBloodDonors' : IDL.Func([], [IDL.Vec(BloodDonor)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'hospitalCount' : IDL.Nat,
            'volunteerCount' : IDL.Nat,
            'availableBeds' : IDL.Nat,
            'donorCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getDonorsByBloodType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BloodDonor)],
        ['query'],
      ),
    'getEmergencyAlerts' : IDL.Func([], [IDL.Vec(EmergencyAlert)], ['query']),
    'getEmergencyContactsByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(EmergencyContact)],
        ['query'],
      ),
    'getHospitals' : IDL.Func([], [IDL.Vec(Hospital)], ['query']),
    'getMyEmergencyContacts' : IDL.Func(
        [],
        [IDL.Vec(EmergencyContact)],
        ['query'],
      ),
    'getSOSEvents' : IDL.Func([], [IDL.Vec(SOSEvent)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVolunteers' : IDL.Func([], [IDL.Vec(Volunteer)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'postEmergencyAlert' : IDL.Func([EmergencyAlert], [IDL.Nat], []),
    'recordSOS' : IDL.Func([SOSEvent], [IDL.Nat], []),
    'registerBloodDonor' : IDL.Func([BloodDonor], [IDL.Nat], []),
    'registerVolunteer' : IDL.Func([Volunteer], [IDL.Nat], []),
    'removeEmergencyContact' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateHospital' : IDL.Func([Hospital], [], []),
  });
};

export const init = ({ IDL }) => { return []; };