/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BloodDonor {
  'id' : bigint,
  'bloodType' : string,
  'contact' : string,
  'city' : string,
  'name' : string,
  'registeredAt' : Time,
}
export interface EmergencyAlert {
  'id' : bigint,
  'alertType' : string,
  'authorId' : [] | [Principal],
  'description' : string,
  'timestamp' : Time,
  'location' : string,
}
export interface EmergencyContact {
  'id' : bigint,
  'relationship' : string,
  'ownerPrincipal' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'phone' : string,
}
export interface Hospital {
  'id' : bigint,
  'lat' : number,
  'lng' : number,
  'contact' : string,
  'name' : string,
  'bedsAvailable' : bigint,
  'address' : string,
}
export interface SOSEvent {
  'id' : bigint,
  'lat' : number,
  'lng' : number,
  'userId' : [] | [Principal],
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'contact' : string,
  'city' : string,
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Volunteer {
  'id' : bigint,
  'city' : string,
  'name' : string,
  'isActive' : boolean,
  'skills' : Array<string>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Add a new emergency contact for authenticated user. Returns contact ID.
   */
  'addEmergencyContact' : ActorMethod<[string, string, string], bigint>,
  /**
   * / Add a hospital. Admin only.
   */
  'addHospital' : ActorMethod<[Hospital], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Get hospitals sorted by proximity (distance calculation done client-side).
   * / Public read.
   */
  'findHospitalsByDistance' : ActorMethod<[number, number], Array<Hospital>>,
  /**
   * / Get all blood donors. Public read.
   */
  'getBloodDonors' : ActorMethod<[], Array<BloodDonor>>,
  /**
   * / Get the calling user's own profile. Requires authenticated user.
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Get summary statistics for the dashboard. Public read.
   */
  'getDashboardStats' : ActorMethod<
    [],
    {
      'hospitalCount' : bigint,
      'volunteerCount' : bigint,
      'availableBeds' : bigint,
      'donorCount' : bigint,
    }
  >,
  /**
   * / Get donors filtered by blood type. Public read.
   */
  'getDonorsByBloodType' : ActorMethod<[string], Array<BloodDonor>>,
  /**
   * / Get all emergency alerts sorted by most recent first. Public read.
   */
  'getEmergencyAlerts' : ActorMethod<[], Array<EmergencyAlert>>,
  /**
   * / Admin/internal function to get emergency contacts for a specific principal
   */
  'getEmergencyContactsByPrincipal' : ActorMethod<
    [Principal],
    Array<EmergencyContact>
  >,
  /**
   * / Get all hospitals. Public read.
   */
  'getHospitals' : ActorMethod<[], Array<Hospital>>,
  /**
   * / Get all emergency contacts for the calling user.
   */
  'getMyEmergencyContacts' : ActorMethod<[], Array<EmergencyContact>>,
  /**
   * / Get all SOS events. Admin only (sensitive location data).
   */
  'getSOSEvents' : ActorMethod<[], Array<SOSEvent>>,
  /**
   * / Fetch any user's profile. Users can only view their own; admins can view anyone's.
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / Get all volunteers. Public read.
   */
  'getVolunteers' : ActorMethod<[], Array<Volunteer>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Post an emergency alert. Requires authenticated user.
   */
  'postEmergencyAlert' : ActorMethod<[EmergencyAlert], bigint>,
  /**
   * / Record an SOS event. Accessible to everyone including unauthenticated
   * / users because SOS must work before login.
   */
  'recordSOS' : ActorMethod<[SOSEvent], bigint>,
  /**
   * / Register as a blood donor. Requires authenticated user.
   */
  'registerBloodDonor' : ActorMethod<[BloodDonor], bigint>,
  /**
   * / Register as a volunteer. Requires authenticated user.
   */
  'registerVolunteer' : ActorMethod<[Volunteer], bigint>,
  /**
   * / Remove an emergency contact by its ID for the calling user.
   */
  'removeEmergencyContact' : ActorMethod<[bigint], undefined>,
  /**
   * / Save / update the calling user's own profile. Requires authenticated user.
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Update an existing hospital. Admin only.
   */
  'updateHospital' : ActorMethod<[Hospital], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];