/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BloodDonor {
  'id' : bigint,
  'contact' : string,
  'proofText' : string,
  'city' : string,
  'name' : string,
  'detectedBloodType' : string,
  'verifiedBloodType' : string,
  'registeredAt' : Time,
}
export interface EmergencyAlert {
  'id' : bigint,
  'alertType' : string,
  'authorId' : [] | [Principal],
  'description' : string,
  'timestamp' : Time,
  'location' : string,
}
export interface EmergencyContact {
  'id' : bigint,
  'relationship' : string,
  'ownerPrincipal' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'phone' : string,
}
export interface Hospital {
  'id' : bigint,
  'lat' : number,
  'lng' : number,
  'contact' : string,
  'name' : string,
  'bedsAvailable' : bigint,
  'address' : string,
}
export interface SOSEvent {
  'id' : bigint,
  'lat' : number,
  'lng' : number,
  'userId' : [] | [Principal],
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'contact' : string,
  'city' : string,
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Volunteer {
  'id' : bigint,
  'proofText' : string,
  'city' : string,
  'name' : string,
  'isActive' : boolean,
  'skills' : Array<string>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBloodDonor' : ActorMethod<
    [string, string, string, string, string],
    { 'error' : string } |
      { 'success' : bigint }
  >,
  'addEmergencyContact' : ActorMethod<[string, string, string], bigint>,
  'addGalleryItem' : ActorMethod<[string], bigint>,
  'addHospital' : ActorMethod<[Hospital], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'findHospitalsByDistance' : ActorMethod<[number, number], Array<Hospital>>,
  'getBloodDonors' : ActorMethod<[], Array<BloodDonor>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'hospitalCount' : bigint,
      'volunteerCount' : bigint,
      'availableBeds' : bigint,
      'donorCount' : bigint,
    }
  >,
  'getDonorsByBloodType' : ActorMethod<[string], Array<BloodDonor>>,
  'getEmergencyAlerts' : ActorMethod<[], Array<EmergencyAlert>>,
  'getEmergencyContactsByPrincipal' : ActorMethod<
    [Principal],
    Array<EmergencyContact>
  >,
  'getGalleryItems' : ActorMethod<[], Array<[bigint, string]>>,
  'getHospitals' : ActorMethod<[], Array<Hospital>>,
  'getMyEmergencyContacts' : ActorMethod<[], Array<EmergencyContact>>,
  'getSOSEvents' : ActorMethod<[], Array<SOSEvent>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVolunteers' : ActorMethod<[], Array<Volunteer>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'postEmergencyAlert' : ActorMethod<[EmergencyAlert], bigint>,
  'recordSOS' : ActorMethod<[SOSEvent], bigint>,
  'registerVolunteer' : ActorMethod<[Volunteer], bigint>,
  'removeEmergencyContact' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateHospital' : ActorMethod<[Hospital], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];